# Simple Metrics - Running it back

The goal of this notebook is to take a step back from the more experimental metrics and get a baseline understanding of the two main datasets we're looking at. This is to be done with simple paper count and citation count metrics, as well as by putting the fields of study to the side to avoid complicating things further.

In [1]:
import pandas as pd
import numpy as np

In [3]:
bdf = pd.read_csv('/bgfs/mrfrank/nolan/threelistfilterAllPapers.csv')
bdf

,Paper ID,Indexed Abstract,A,B,C
0,2095588566,"{""indexlength"":151,""invertedindex"":{""based"":[0...",True,True,True
1,2252279066,"{""indexlength"":542,""invertedindex"":{""today"":[0...",True,True,True
2,2505312253,"{""indexlength"":1508,""invertedindex"":{""issn:"":[...",True,True,True
3,2552604832,"{""indexlength"":240,""invertedindex"":{""summary"":...",True,True,True
4,1963480011,"{""indexlength"":149,""invertedindex"":{""street"":[...",True,True,True
...,...,...,...,...,...
2200477,2394482995,"{""indexlength"":199,""invertedindex"":{""an"":[0],""...",True,True,True
2200478,2240119898,"{""indexlength"":605,""invertedindex"":{""introduct...",True,True,True
2200479,27485236,"{""indexlength"":356,""invertedindex"":{""the"":[0,1...",True,True,True
2200480,2232604002,"{""indexlength"":253,""invertedindex"":{""accurate""...",True,True,True
2200481,2172300891,"{""indexlength"":181,""invertedindex"":{""filtering...",True,True,True

In [10]:
papers = pd.read_csv('/bgfs/mrfrank/datawarehouse/MAG/NEW_MAG/Papers.txt', sep = '\t', names=[
                                      "Paper ID",
                                      "Rank",
                                      "Doi string",
                                      "Doc type",
                                      "Paper title",
                                      "Original title",
                                      "Book title string",
                                      "Year",
                                      "Date",
                                      #"Online date",
                                      "Publisher",
                                      "Journal ID",
                                      "Conference Series ID",
                                      "Conference instance ID",
                                      "Volume",
                                      "Issue",
                                      "First page",
                                      "Last page",
                                      "Reference count",
                                      "Citation count",
                                      "Estimated citation",
                                      "Original venue",
                                      #"Family ID",
                                      #"Family rank",
                                      "Created Date"])
papers = papers[['Paper ID', 'Paper title', 'Year', 'Date', 'Reference count', 'Citation count']]

/ihome/crc/install/python/ondemand-jupyter-python3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (12,13,14,15,16) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [12]:
ap = pd.read_csv('/bgfs/mrfrank/datawarehouse/MAG/NEW_MAG/PaperAuthorAffiliations.txt',
                 sep = '\t', 
                 names = ['Paper ID', 'Author ID', 'Affiliation ID', 'Author sequence number'])

In [16]:
affils = pd.read_csv("/bgfs/mrfrank/datawarehouse/MAG/NEW_MAG/Affiliations.txt",sep="\t",header=None,
                                           names=[
                                               "Affiliation ID",
                                               "Rank",
                                               "Affiliation name",
                                               "Display name",
                                               "Paper count",
                                               "Citation count"
                                           ],
                                           index_col=0,
                                           engine='c',
        )
affils = affils[['Affiliation name']]
affils

Memory usage of properties dataframe is : 0.85693359375  MB
******************************
Column:  Rank
dtype before:  int64
dtype after:  uint16
******************************
******************************
Column:  Paper count
dtype before:  int64
dtype after:  uint32
******************************
******************************
Column:  Citation count
dtype before:  int64
dtype after:  uint32
******************************
___MEMORY USAGE AFTER COMPLETION:___
Memory usage is:  0.60699462890625  MB
This is  70.83333333333333 % of the initial size

                                               Affiliation name
Affiliation ID
858948344        canadian foundation for healthcare improvement
35427347                        islamic university of indonesia
35462925                  southern connecticut state university
98298690                                      i shou university
165075387                                      trine university
...                                                         ...
199752191       american association of variable star observers
335064146                automobile club of southern california
203847022                       polytechnic institute of lisbon
19370010                                             orange s a
1344073410                      howard hughes medical institute

[18720 rows x 1 columns]

In [ ]:
bdfpap = papers[papers['Paper ID'].isin(bdf['Paper ID'])]

In [17]:
papaffil = pd.merge(bdfpap, ap, on = 'Paper ID', how = 'inner')

In [19]:
paa = pd.merge(papaffil, affils, on = 'Affiliation ID', how = 'left')
paa

,Paper ID,Paper title,Year,Date,Reference count,Citation count,Author ID,Affiliation ID,Author sequence number,Author name,Last known affiliation ID,Affiliation name
0,1819117828,the distinctive feature of weak interactions a...,2001,2001-04-01,2,0,2481555453,32699454,1,kh m beshtoev,3.269945e+07,joint institute for nuclear research
1,2771061228,compresseur a vis a flux axial,2006,2006-12-04,0,0,2055413202,1332737386,3,oladapo fakunle,1.332737e+09,general electric
2,2771061228,compresseur a vis a flux axial,2006,2006-12-04,0,0,126005442,1332737386,1,kurt david murrow,1.332737e+09,general electric
3,2771061228,compresseur a vis a flux axial,2006,2006-12-04,0,0,2734780661,1332737386,2,rollin george griffin,1.332737e+09,general electric
4,559973243,junos enterprise switching,2009,2009-01-01,0,1,2131998856,4604,2,doug marschke,4.604000e+03,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
454662629,2232604002,sharp iii first use of adaptive optics imaging...,2016,2016-11-11,72,12,2229205609,84653119,1,geoff c f chen,8.465312e+07,academia sinica
454662630,2232604002,sharp iii first use of adaptive optics imaging...,2016,2016-11-11,72,12,2119632286,84653119,3,kenneth c wong,8.465312e+07,academia sinica
454662631,2232604002,sharp iii first use of adaptive optics imaging...,2016,2016-11-11,72,12,2528058560,149899117,12,simona vegetti,1.498991e+08,max planck society
454662632,2232604002,sharp iii first use of adaptive optics imaging...,2016,2016-11-11,72,12,2084521563,241749,8,matthew w auger,2.417490e+05,university of cambridge
454662633,2232604002,sharp iii first use of adaptive optics imaging...,2016,2016-11-11,72,12,2233774079,9341345,6,a halkola,9.341345e+06,university of lubeck

In [20]:
bfdf = paa[['Paper ID', 'Paper title', 'Year', 'Reference count', 'Citation count', 'Affiliation ID', 'Affiliation name']]

In [23]:
bfdf.to_csv('/bgfs/mrfrank/nolan/MAG/Data/BroadDF_Affils.csv')